import { STATE_NAMES, type StateName } from '@/types/project'
import { useAppStore } from '@/store'

/**
 * Cross-state character size / position normalizer.
 *
 * Problem: each state's sheet is generated by an independent AI call, so
 * character bbox size and centering varies between states (Idle = 252 px
 * tall, Recording = 213 px tall, etc.). When mori-desktop swaps between
 * states at runtime, the character visibly shrinks/grows/shifts.
 *
 * Solution: stamp each state with a CellTransform (scale + offsetX +
 * offsetY) that's applied at render-time over the sheet. Underlying
 * sheet pixels stay untouched — transform is purely a viewing/export-time
 * post-process.
 */

type Bbox = { x: number; y: number; w: number; h: number; cx: number; cy: number }

/**
 * Measure character bbox of frame 1 of a sheet (assumes 4×4 grid with the
 * top-left cell being representative of the state's pose framing — frames
 * within a state are already locked, so any frame works).
 */
async function measureFrame1Bbox(sheet: Blob): Promise<Bbox | null> {
  const bmp = await createImageBitmap(sheet)
  const canvas = new OffscreenCanvas(256, 256)
  const ctx = canvas.getContext('2d')!
  ctx.drawImage(bmp as unknown as CanvasImageSource, 0, 0, 256, 256, 0, 0, 256, 256)
  const img = ctx.getImageData(0, 0, 256, 256)
  let minX = 256, maxX = 0, minY = 256, maxY = 0, found = false
  for (let y = 0; y < 256; y++) {
    for (let x = 0; x < 256; x++) {
      if (img.data[(y * 256 + x) * 4 + 3] > 32) {
        if (x < minX) minX = x
        if (x > maxX) maxX = x
        if (y < minY) minY = y
        if (y > maxY) maxY = y
        found = true
      }
    }
  }
  if (!found) return null
  return {
    x: minX, y: minY,
    w: maxX - minX + 1, h: maxY - minY + 1,
    cx: Math.round((minX + maxX) / 2),
    cy: Math.round((minY + maxY) / 2),
  }
}

/**
 * Scan every state's sheet and compute its character bbox.
 * Returns the measurements (callers may want them for UI display).
 */
export async function measureAllStates(): Promise<Record<StateName, Bbox | null>> {
  const store = useAppStore.getState()
  const result = {} as Record<StateName, Bbox | null>
  for (const name of STATE_NAMES) {
    const sheet = store.project.states[name].sheet
    result[name] = sheet ? await measureFrame1Bbox(sheet) : null
  }
  return result
}

/**
 * Auto-normalize: scan all states' bboxes, compute per-state transform so
 * every state's character lands at the SAME height, CENTERED in the cell.
 *
 * @param targetHeight pixels (out of 256 cell height). Default = median of
 *                     measured heights (minimizes total visual jump from
 *                     current state). Common manual values: 200 (more
 *                     margin), 220 (current Mori avg), 240 (max).
 *
 * @returns the transforms applied per state, plus the chosen target height
 */
export async function normalizeAllStates(
  targetHeight?: number,
): Promise<{ target: number; applied: Record<StateName, { scale: number; offsetX: number; offsetY: number }> }> {
  const store = useAppStore.getState()
  const measurements = await measureAllStates()

  const heights = STATE_NAMES
    .map((n) => measurements[n])
    .filter((b): b is Bbox => b !== null)
    .map((b) => b.h)
  if (heights.length === 0) {
    throw new Error('No sheets to normalize')
  }

  const target = targetHeight ?? median(heights)
  const applied = {} as Record<StateName, { scale: number; offsetX: number; offsetY: number }>

  const cellCenter = 128 // 256 / 2

  for (const name of STATE_NAMES) {
    const bb = measurements[name]
    if (!bb) {
      applied[name] = { scale: 1, offsetX: 0, offsetY: 0 }
      continue
    }
    const scale = target / bb.h
    // After scaling cell around cellCenter, bbox center moves to:
    //   cellCenter + (bb.cx - cellCenter) * scale
    // We want bbox center at cellCenter, so offset compensates:
    const offsetX = (cellCenter - bb.cx) * scale
    const offsetY = (cellCenter - bb.cy) * scale
    applied[name] = { scale, offsetX: Math.round(offsetX), offsetY: Math.round(offsetY) }
    store.updateState(name, { transform: applied[name] })
  }

  return { target, applied }
}

/**
 * Apply a CellTransform to a single cell when drawing. Use within a
 * canvas 2D context after positioning at the cell's top-left corner.
 *
 * Scales the cell around its own center, then offsets in pixel coords.
 *
 * @param ctx        the canvas context (already positioned at cell origin)
 * @param source     source bitmap/canvas to draw (assumed cellSize × cellSize)
 * @param cellSize   width/height of cell (typically 256)
 * @param transform  the {scale, offsetX, offsetY} to apply
 */
export function drawCellWithTransform(
  ctx: CanvasRenderingContext2D | OffscreenCanvasRenderingContext2D,
  source: CanvasImageSource,
  sx: number, sy: number, sw: number, sh: number,
  dx: number, dy: number, dw: number, dh: number,
  transform: { scale: number; offsetX: number; offsetY: number },
): void {
  ctx.save()
  // Translate to cell center + manual offset
  ctx.translate(dx + dw / 2 + transform.offsetX * (dw / sw), dy + dh / 2 + transform.offsetY * (dh / sh))
  // Scale around new origin
  ctx.scale(transform.scale, transform.scale)
  // Move back so cell top-left maps correctly
  ctx.drawImage(source, sx, sy, sw, sh, -dw / 2, -dh / 2, dw, dh)
  ctx.restore()
}

function median(nums: number[]): number {
  const sorted = [...nums].sort((a, b) => a - b)
  const mid = Math.floor(sorted.length / 2)
  return sorted.length % 2 === 0
    ? (sorted[mid - 1] + sorted[mid]) / 2
    : sorted[mid]
}
