import type { StateName } from '@/types/project'

// Pose-focused semantic descriptions for each state. These feed into AI
// prompts as {{state_semantics}}. Visual character traits (hair color,
// outfit, ears, proportions) come from the user's reference image — these
// strings focus only on POSE, GESTURE, EXPRESSION so the AI knows what
// the character is DOING in each state.
//
// Calibrated against mori-desktop's canonical placeholder set
// (~/mori-universe/mori-desktop/docs/sprites/mori-*.png).
export const DEFAULT_STATE_SEMANTICS: Record<StateName, string> = {
  idle:
    'standing front-facing, gentle inviting closed-mouth smile, eyes open and looking softly forward, arms relaxed at the sides (hands hidden inside long sleeves is fine), calm serene welcoming presence',

  sleeping:
    'sitting cross-legged with knees folded close to body, eyes closed in a peaceful closed-eye smile, hands resting gently in lap, body curled small and cozy, a tiny stylized "Z" or "Zz" floating near the head to indicate sleep',

  recording:
    'IMPORTANT CONTEXT: this state is "the character LISTENING to the user talk" (the user speaks INTO the computer; the desktop pet hears it). The character is the LISTENER, not the speaker. NOT performing / singing / speaking into a mic. NO microphone, NO megaphone, NO recording device, NO prop in hand. Pose: wide open alert eyes (round and bright), open attentive listening smile, ONE empty hand raised up beside the ear in an "I am listening, please continue" cupped-hand gesture (hand cups the ear like trying to hear better). Other hand stays at side or hidden. Light motion lines or small sparkles around the figure to suggest attentive energy. Both hands stay empty — character holds nothing.',

  thinking:
    'one finger raised lightly to temple or forehead in a pondering gesture, eyes glancing up and to one side contemplatively, slight closed-mouth thoughtful expression, a few small sparkles or thought-marks floating around the head to suggest active thought',

  done:
    'CELEBRATION BURST — the user just finished a task and the character is genuinely thrilled for them. This is a ONE-SHOT animation: brief, intense, energetic, like "YAY you did it!!". Eyes closed in a wide joyful ^v^ curve, mouth wide open in a delighted shouting-with-joy smile, BOTH hands raised UP high in a victory / cheering / celebratory gesture (think kids cheering, arms up like fireworks bursting). Full-body joyful energy — small forward bounce, slight head tilt back in delight, optional small sparkles or confetti bursting around. This is NOT a calm prayer / NOT a quiet thank-you — it is enthusiastic celebration energy.',

  error:
    'PANIC / DISTRESS BURST — the user triggered an error and the character is dramatically overwhelmed about it. This is a ONE-SHOT animation: brief, exaggerated, "oh no the sky is falling!" energy. Pose: BOTH hands clutched to the sides of the head in a "head in hands / oh no!" gesture (palms cradling temples, fingers spread). Eyes either squeezed shut in worry OR wide and teary. Mouth small open in distressed "ah!" expression. Body slightly hunched / leaning forward in distress. Optional accents: small tear at corner of eye, distress sweat-drop, "//" tension lines near head, motion lines suggesting panic. NOT cowering in fear, NOT angry, NOT sobbing tragically — this is CUTE OVERWHELMED WORRY like "I tried but it broke, sorry sorry!".',

  // NOTE: walking/dragging semantics describe the STATIC BASE pose
  // (which is a neutral full-body reference, not a walking pose), NOT
  // the animation motion. The actual walking gait / dragging swing is
  // generated by the W / Dr templates from this neutral reference.
  // This split is deliberate: a static walking-mid-stride pose used as
  // reference would anchor AI to that specific pose, killing the gait
  // cycle in the 16-frame sheet.
  walking:
    'NEUTRAL FULL-BODY STANDING REFERENCE for walking animation. Pose: standing front-facing or slight three-quarter view, BOTH FEET PLANTED on the ground (left and right shoes both visible), legs straight, hands relaxed at sides, body upright. ENTIRE body visible from top of hair to bottom of shoes — head not cropped, feet not cropped, both feet fully shown. Cheerful determined expression, eyes looking forward. NO walking pose (do not lift either leg, do not show mid-stride). NO held items. This static is the IDENTITY + PROPORTIONS reference for walking — the actual walking gait cycle is rendered later in 16 separate frames.',

  dragging:
    'NEUTRAL FULL-BODY REFERENCE for dragging animation. Pose: standing front-facing, BOTH FEET visible (planted lightly on ground for the static — the actual lifted-off-ground effect is rendered later in 16 frames). Full body from hair-top to shoe-bottom shown, body upright, arms at sides. Pleasantly surprised expression (slight "oh!" eyes + small open smile) to hint at the dragging emotional tone. NO ropes / strings / lifting visible in the static — those appear in the animation phase. NO held items. This static is the IDENTITY + PROPORTIONS reference; the swing motion + feet-off-ground come later.',
}
